const SET_IS_ADMIN = 'SET_IS_ADMIN';
const SET_EMAIL = 'SET_EMAIL';
const SET_TOURNAMENT = 'SET_TOURNAMENT';
const SET_DEADLINES = 'SET_DEADLINES';

export default {
	SET_IS_ADMIN,
	SET_EMAIL,
	SET_TOURNAMENT,
	SET_DEADLINES
};